### ISSUE TITLE
Can't download specific versions of EDD-hosted plugins

### ISSUE THREAD

**Issue by chrisvanpatten** [junaidbhura/composer-wp-pro-plugins#10]
While working on my PR (#9) I noticed that the behaviour around EDD-hosted plugins is a little confusing.

It turns out, the [EDD Licensing API `check_version` endpoint](https://docs.easydigitaldownloads.com/article/384-software-licensing-api) only returns the _latest_ version of a plugin.

I believe, generally, the `version` parameter is ignored or only used for analytics/tracking purposes.

Caveat: It's possible that some EDD installs were customised to allow downloading older versions, but I have tested a few different EDD sites for plugins I own, and haven't been able to find any that do.

**Comment by junaidbhura** [comment]
Hey @chrisvanpatten that's right, this is also a problem with Gravity Forms.

For some reason, they've chosen not to add in this feature! I'm updating the README file of this repository to reflect this.
