### ISSUE TITLE
Build URLs with http_build_query()

### ISSUE THREAD

**Issue by szepeviktor** [junaidbhura/composer-wp-pro-plugins#12]
Do you agree?
May I send a PR?

**Comment by junaidbhura** [comment]
@szepeviktor Could you please elaborate this?

**Comment by szepeviktor** [comment]
Currently the code concatenates string literals with variables. This may be error prone and hard to read

```php
$response = unserialize( $http->post( 'https://www.gravityhelp.com/wp-content/plugins/gravitymanager/api.php?op=get_plugin&slug=' . $this->slug . '&key=' . getenv( 'GRAVITY_FORMS_KEY' ) ) );
```

but here comes http_build_query() (something like this)

```php
const API_BASE_URL = 'https://www.gravityhelp.com/wp-content/plugins/gravitymanager/api.php';

$queryVars = [
	'op' => 'get_plugin',
    'slug' => $this->slug,
    'key' => getenv( 'GRAVITY_FORMS_KEY' ),
];
$queryString = http_build_query( $queryVars );
$url = sprintf( '%s?%s', self::API_BASE_URL, $queryString );
$response = unserialize( $http->post( $url ) );
```

**Comment by junaidbhura** [comment]
@szepeviktor Sure, that makes sense.

I'll add this in. Just so you know, I'm planning a bit of a rewrite of this plugin. I'm going to be adding in unit tests, and coding standard checks. You can feel free to create any issues, and we can have a discussion on what direction to take, but I'd request you to hold off on creating any pull requests, as it might be hard for me to merge it in.

**Comment by szepeviktor** [comment]
@junaidbhura I work with developer teams, running code they write.

I talk them into at least these 3 zero-coverage tests.

1. syntax check: parallel-lint
1. coding standard: https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/Continuous-integration-Continuous-delivery.md#coding-style--coding-standard
1. static analysis: @phpstan

All these need nearly no code to run.

**Comment by junaidbhura** [comment]
Thanks for your feedback @szepeviktor . I'm going to be using CircleCI to check for WordPress coding standards and PHPUnit for unit tests.

**Comment by szepeviktor** [comment]
Okay!
Then I talk you into using the 2 remaining tests :)

**Comment by junaidbhura** [comment]
Haha, I'll look into it @szepeviktor and prioritize development as needed! This is a really simple plugin, so I really don't want to over-engineer it.

**Comment by szepeviktor** [comment]
This is localheinz's baseline https://github.com/localheinz/php-library-template

**Comment by junaidbhura** [comment]
Thanks, I'll take a look! And here's mine 😉

https://github.com/junaidbhura/wp-project-base
