### ISSUE TITLE
Support/documentation: what is registered URL?

### ISSUE THREAD

**Issue by xaqrox** [junaidbhura/composer-wp-pro-plugins#13]
I want to use this plugin to require WP All Import, but I have no idea what the "registered url" env variable is supposed to be. Can you provide some advice on where to find that in my wpallimport.com account?

**Comment by junaidbhura** [comment]
Hi @xaqrox that would be your website's URL. The one for which the license is issued.

**Comment by xaqrox** [comment]
Thanks for the reply. As far as I can tell there is no website associated. The label for the key says "WP All Import – WP All Import Unlimited License"

**Comment by junaidbhura** [comment]
Then you can just use the URL of the website you are using it on :)
