### ISSUE TITLE
Polylang username & password

### ISSUE THREAD

**Issue by alexanderdejong** [junaidbhura/composer-wp-pro-plugins#15]
Hi @junaidbhura, thank you for creating this package! I just have a question regarding Polylang.

What URL should I put in the POLYLANG_PRO_URL variable? I've added the download URL from Polylang but then I get asked for my username and password. 

Is there someway that we can add these to the package as wel as an env variable? I ask because I would like to use your package in combination with continuous delivery. 

Thanks again for your work and look forward to hearing from you.
-Alexander

**Comment by junaidbhura** [comment]
Hi @alexanderdejong the `POLYLANG_PRO_URL` should be the URL of the site to which the license belongs. Hope that helps!

**Comment by certainlyakey** [comment]
> Is there someway that we can add these to the package as wel as an env variable? I ask because I would like to use your package in combination with continuous delivery.

@alexanderdejong you can use `auth.json` to do that 🙂 roughly should be like this: 

```
{
  "http-basic": {
      "polylang.pro": {
          "username": "email",
          "password": "password"
      }
  }
}
```
