### ISSUE TITLE
Support for Composer 2

### ISSUE THREAD

**Issue by mcaskill** [junaidbhura/composer-wp-pro-plugins#19]
Composer 2.0 is getting closer to a stable release and this plugin will need an update, as per: https://github.com/composer/composer/issues/8726

Thanks

**Comment by junaidbhura** [comment]
Thanks @mcaskill , I'll push an update shortly

**Comment by mcaskill** [comment]
As one can tell from the list of commits referenced by GitHub in this issue, I am working on a future pull request to add support for Composer v2.

I am collaborating with [ffraenz/private-composer-installer](https://github.com/ffraenz/private-composer-installer) on some Composer plugin API issues that are preventing us from moving forward.

**Comment by junaidbhura** [comment]
Thanks @mcaskill !
