### ISSUE TITLE
Must-Use Plugin Issue

### ISSUE THREAD

**Issue by jameelmoses** [junaidbhura/composer-wp-pro-plugins#26]
I'm having an issue getting Gravity Forms to install as a [must-use plugin](https://wordpress.org/support/article/must-use-plugins/). ACF Pro goes to the `mu-plugins` directory as expected, but Gravity Forms is still going to `plugins`

```
"extra": {
    "installer-paths": {
      "web/app/mu-plugins/{$name}/": [
        "type:wordpress-muplugin",
        "junaidbhura/advanced-custom-fields-pro",
        "junaidbhura/gravity-forms"
      ],
      "web/app/plugins/{$name}/": [
        "type:wordpress-plugin"
      ],
      "web/app/themes/{$name}/": [
        "type:wordpress-theme"
      ]
    },
    "wordpress-install-dir": "web/wp"
  }
```

Any advice here?

**Comment by mcaskill** [comment]
I believe `junaidbhura/gravity-forms` should be `junaidbhura/gravityforms`.

If it still doesn't work, what does your `repositories` section look like?

**Comment by junaidbhura** [comment]
Thanks @mcaskill

**Comment by jameelmoses** [comment]
That was the issue.

Whelp....that's enough internet for today. :sweat_smile:
