### ISSUE TITLE
Plans for future supported plugins?

### ISSUE THREAD

**Issue by broskees** [junaidbhura/composer-wp-pro-plugins#32]
This project seems like a great time saver. Are there plans to support more premium plugins out of the box?

**Comment by junaidbhura** [comment]
Hi there I'm glad you find this project useful :) 

I usually just add plugins that I come across. Folks are welcome to create Pull Requests for any plugins they'd like to add as well.

I'm closing this issue for now, but please feel free to continue this conversation!
