### ISSUE TITLE
The "https://www.wpallimport.com/" file could not be downloaded (HTTP/2 503 )

### ISSUE THREAD

**Issue by justlevine** [junaidbhura/composer-wp-pro-plugins#41]
Composer started erroring on me yesterday after working fine for months, when trying to grab WPAI

```
In CurlDownloader.php line 623:

  The "https://www.wpallimport.com/" file could not be downloaded (HTTP/2 503 )
```

Running with debug doesnt change things either:

![image](https://user-images.githubusercontent.com/29322304/208009670-e67df095-330b-4fd9-a44b-aee686ec0e88.png)

Updating to v1.5.0 didnt change anything either...

Any ideas?

**Comment by junaidbhura** [comment]
Hi @justlevine I've faced this issue too. Looks like WP All Import recently started using Cloudflare - where the CLI downloads are disabled. I've created a support ticket with them. Will keep you updated here on this ticket about progress.

This means that unfortunately:

**As of right now, WP All Import / Export remains broken, until they allow downloads from their server.**

**Comment by justlevine** [comment]
It's comforting to know it's not just me at least. Thanks for the prompt reply!

**Comment by jmotes** [comment]
Strangely, it works fine for me locally after upgrading to v1.5. It still fails when ran on our Azure Devops CI/CD build agent though:

```
The "https://www.wpallimport.com/edd-sl/package_download/[MY_TOKEN]" file could not be downloaded (HTTP/2 503 )
```

It adds the token to the URL with v1.5 and I can download it via the same URL in a browser after Cloudflare deems the connection secure.

**Comment by justlevine** [comment]
@jmotes probably because the old zip is cached by Composer locally?

**Comment by jmotes** [comment]
@justlevine I had deleted my vendors directory before trying. I think maybe it was because I validated my connection in a browser on the same machine I ran `composer install` on.

Anyhow, I got a response back from Soflyy yesterday after I created a support ticket. They've made some adjustments to Cloudflare and everything's working fine for me now!

**Comment by justlevine** [comment]
Same here :-)

**Comment by mattneal-stafflink** [comment]
I'm still having some issues:

```
Install of junaidbhura/wp-all-import-pro failed
 [UnexpectedValueException]
  'C:\Users\matty\github\gphvendor/composer/tmp-ed3380115055df89bcf97d0cd89c
  69ec' is not a zip archive.
```
Seems to be happening on Windows 10/11 only? Very odd. Gravity Forms and ACF work still. I don't have this issue on my Mac though. 

I've tried composer 2.2.12, 2.5.4, and a few others. I'm not sure if junaidbhura/composer-wp-pro-plugins is actually the issue. I can see that the WpAiPro.php has a valid response with the correct link. `return $response['download_link'];` is returning a valid link, but it doesn't seem to work after that. I've even tried downloading the link it generates in my browser, and it works perfectly. I'm stuck from here though...

**Comment by ghost** [comment]
@mattneal-stafflink just in-case it helps unblock you, I've resorted to using WSL2 on Windows 11 for my local development. It works fine there for me using composer 2.4.2.

**Comment by mattneal-stafflink** [comment]
> @mattneal-stafflink just in-case it helps unblock you, I've resorted to using WSL2 on Windows 11 for my local development. It works fine there for me using composer 2.4.2.

That did it. Using WSL2 with ubuntu. No issues.

Thanks for the suggestion!
