### ISSUE TITLE
ACF announces official Composer support for installing ACF PRO

### ISSUE THREAD

**Issue by mcaskill** [junaidbhura/composer-wp-pro-plugins#48]
[Announcement](https://www.advancedcustomfields.com/blog/composer-support-acf-pro/) and [documentation](https://www.advancedcustomfields.com/resources/installing-acf-pro-with-composer/).

> We’ve add a new section to the licenses panel on the [Licenses](https://www.advancedcustomfields.com/my-account/view-licenses/)​​ tab inside [My Account](https://www.advancedcustomfields.com/my-account/). Clicking Install using Composer for your license will reveal a panel where you can generate an auth.json credentials file to be used with Composer.

> ```json5
> // composer.json
> {
> 	"require": {
> 		"wpengine/advanced-custom-fields-pro": "<constraint>"
> 	},
> 	"repositories": [
> 		{
> 			"type": "composer",
> 			"url": "https://connect.advancedcustomfields.com"
> 		}
> 	]
> }
> ```

> ```json5
> // auth.json
> {
>   "http-basic": {
>     "connect.advancedcustomfields.com": {
>       "username": "<license_key>",
>       "password": "<site_url>"
>     }
>   }
> }
> ```

It's unfortunate you were not mentioned in the "Shout out to the maintainers of these packages".

**Comment by junaidbhura** [comment]
Thanks for sharing @mcaskill - and all your hard work to keep this project going. I personally think using environment variables is perhaps a better solution than using `auth.json` so we can keep ACF Pro on this package for as long as it is supported.

You definitely deserve a shout-out for your effort on this project 👏

**Comment by mcaskill** [comment]
> I personally think using environment variables is perhaps a better solution than using `auth.json`

Same; especially when one requires many pro plugins in the same project, keep all those keys together.

**Comment by mcaskill** [comment]
PivvenIT [announces](https://github.com/pivvenit/acf-composer-bridge/commit/14e45a27f61e1980e1fa6f8709b5ba8e2c6fc021) the shutting down of [ACF Pro Composer Bridge](https://github.com/pivvenit/acf-composer-bridge) on 2023-06-01 in favour of first-party support.
