### ISSUE TITLE
Class Wpml does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by Twansparant** [junaidbhura/composer-wp-pro-plugins#54]
Hi Junaid,

Really happy to see WPML support in your latest release, awesome!
However when I upgrade to the latest version, I get this warning:

```bash
Class Junaidbhura\Composer\WPProPlugins\Plugins\Wpml located in ./vendor/junaidbhura/composer-wp-pro-plugins/plugins/WPML.php does not comply with psr-4 autoloading standard. Skipping.
```

Are you already aware of this?

**Comment by mcaskill** [comment]
Huh. I thought I renamed the file accordingly.
Git or my non-case-sensitive OS must not have taken my file rename seriously.

**Comment by mcaskill** [comment]
@junaidbhura When you have a chance, can you rename the file to match the class name?

I don't think we need a pull request to resolve this mistake. Furthermore, if you want, you can add me as a maintainer to help out.

**Comment by mattneal-stafflink** [comment]
+1 for fixing this. No biggie, but still!

**Comment by junaidbhura** [comment]
Hey @Twansparant a new version `1.8.0` has been released. Can you check if that release fixes this issue?

**Comment by Twansparant** [comment]
> Can you check if that release fixes this issue?

I don't see that warning anymore when running `composer update` so I guess it's fixed! Thanks!

**Comment by mattneal-stafflink** [comment]
> > Can you check if that release fixes this issue?
> 
> I don't see that warning anymore when running `composer update` so I guess it's fixed! Thanks!

Same :)

**Comment by junaidbhura** [comment]
Great! Props to @szepeviktor for the fix!
