### ISSUE TITLE
gravity forms update issue

### ISSUE THREAD

**Issue by Nihal12-dev** [junaidbhura/composer-wp-pro-plugins#62]
Hi Junaid,

Mo from boylen here, was just trying to update one of our site's plugins(gravity forms), i'm currently on composer version 1.10.26 as some of the newer versions were having issues when updating some older sites. I get this error saying " [UnexpectedValueException]
  Expected a valid download URL for package junaidbhura/gravityforms" . Any advise on how to go about resolving this ? the current gravity forms version for this particular site is at 2.4.11 and i'm attempting to upgrade this as composer stops at updating gravity forms and just exits without updating the remaining plugins.

I've also tried updating to the latest composer version and clearing the cache and trying it again but no luck so just rolledback to composer 1.
<img width="857" alt="image" src="https://user-images.githubusercontent.com/61972691/231926673-694f73f2-595d-49f8-ac1d-41bd64aa410b.png">

**Comment by junaidbhura** [comment]
Hey @Nihal12-dev try adding a trailing slash in the composer.json file for gravity forms, example: 

```json
"dist": {
    "type": "zip",
    "url": "https://www.gravityforms.com/"
},
```

**Comment by Nihal12-dev** [comment]
Hi Junaid,

No luck with that unfortunately :/ 
This is what my composer.json looks like : 



{
  "name": "boylen/immanuel-college",
  "description": "Custom website for Immanuel Lutheran College.",
  "repositories":[
    {
      "type":"composer",
      "url":"https://wpackagist.org"
    },
    {
      "type":"vcs",
      "url":"https://github.com/junaidbhura/composer-wp-pro-plugins"
    },
    {
      "type":"vcs",
      "url":"https://github.com/junaidbhura/gumponents"
    },
    {
      "type":"vcs",
      "url":"git@github.com:BoylenStaff/boylen-plus.git"
    },
    {
      "type":"vcs",
      "url":"git@github.com:BoylenStaff/bn-blocks.git"
    },
    {
      "type":"vcs",
      "url":"git@github.com:BoylenStaff/bn-breadcrumbs.git"
    },
    {
      "type":"vcs",
      "url":"git@github.com:BoylenStaff/bn-core.git"
    },
    {
      "type":"vcs",
      "url":"git@github.com:BoylenStaff/bn-events.git"
    },
    {
      "type":"vcs",
      "url":"git@github.com:BoylenStaff/bn-calendar.git"
    },
    {
      "type":"vcs",
      "url":"git@github.com:BoylenStaff/bn-news.git"
    },
    {
      "type":"vcs",
      "url":"git@github.com:BoylenStaff/bn-people.git"
    },
    {
      "type":"vcs",
      "url":"git@github.com:BoylenStaff/bn-seo.git"
    },
    {
      "type":"vcs",
      "url":"git@github.com:BoylenStaff/updraft-plus.git"
    },
    {
      "type":"vcs",
      "url":"git@github.com:BoylenStaff/australian-post.git"
    },
    {
      "type":"vcs",
      "url":"git@github.com:BoylenStaff/WoocommerceWestpacPaywayNet.git"
    },
    {
      "type": "package",
      "package": {
        "name": "junaidbhura/advanced-custom-fields-pro",
        "version": "5.9.5",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "https://www.advancedcustomfields.com"
        },
        "require": {
          "junaidbhura/composer-wp-pro-plugins": "*"
        }
      }
    },
    {
      "type": "package",
      "package": {
        "name": "junaidbhura/gravityforms",
        "version": "2.4.11",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "https://www.gravityforms.com/"
        },
        "require": {
          "junaidbhura/composer-wp-pro-plugins": "*"
        }
      }
    }
  ],
  "extra": {
    "installer-paths": {
      "web/wp-content/mu-plugins/{$name}/": ["type:wordpress-muplugin", "junaidbhura/gumponents", "junaidbhura/advanced-custom-fields-pro"],
      "web/wp-content/plugins/{$name}/": ["type:wordpress-plugin"],
      "web/wp-content/themes/{$name}/": ["type:wordpress-theme"]
    },
    "wordpress-install-dir": "web/wp"
  },
  "require": {
    "php": ">=7.1",
    "roots/wordpress": "6.2",
    "composer/installers": "^1.4",
    "vlucas/phpdotenv": "^4.1.0",
    "oscarotero/env": "^1.1.0",
    "roots/wp-config": "1.0.0",
    "boylenstaff/boylen-plus": "1.0.13",
    "boylenstaff/bn-blocks": "1.0.14",
    "boylenstaff/bn-breadcrumbs": "1.0.1",
    "boylenstaff/bn-core": "1.0.2",
    "boylenstaff/bn-events": "1.0.3",
    "boylenstaff/bn-calendar": "1.0.3",
    "boylenstaff/bn-news": "1.0.3",
    "boylenstaff/bn-people": "1.0.2",
    "boylenstaff/bn-seo": "1.0.0",
    "boylenstaff/updraftplus": "*",
    "boylenstaff/australian-post": "*",
    "boylenstaff/westpac-payway-net": "*",
    "junaidbhura/gumponents": "0.4.0",
    "junaidbhura/advanced-custom-fields-pro": "*",
    "junaidbhura/gravityforms": "*",
    "wpackagist-plugin/wordpress-seo": "*",
    "wpackagist-plugin/woocommerce": "*",
    "wpackagist-plugin/duracelltomi-google-tag-manager": "*",
    "wpackagist-plugin/jetpack": "*",
    "wpackagist-plugin/redirection": "*",
    "wpackagist-plugin/search-exclude": "*",
    "wpackagist-plugin/hotjar": "*",
    "wpackagist-plugin/wp-mail-smtp": "*",
    "wpackagist-plugin/classic-editor": "*",
    "wpackagist-plugin/forms-for-campaign-monitor": "*",
    "wpackagist-plugin/advanced-rich-text-tools": "*",
    "wpackagist-plugin/gallery-custom-links": "*",
    "wpackagist-plugin/wp-2fa": "*",
    "wpackagist-plugin/wp-notification-bars": "*"
  },
  "require-dev": {
    "squizlabs/php_codesniffer": "*",
    "wp-coding-standards/wpcs": "*"
  },
  "scripts": {
    "lint-php": "phpcs"
  },
  "config": {
    "allow-plugins": {
      "junaidbhura/composer-wp-pro-plugins": true,
      "composer/installers": true,
      "roots/wordpress-core-installer": true
    }
  }
}


Let me know if there's anything off about it.

**Comment by junaidbhura** [comment]
@Nihal12-dev the same thing needs to be done for all plugins, example: `https://www.advancedcustomfields.com/`

**Comment by Nihal12-dev** [comment]
Ahhh, the funny part is advanced custom fields seems to be downloading fine without the trailing slash. so i'm not sure if it's something to do with my composer version or maybe a whole another issue that i haven't yet found.

**Comment by junaidbhura** [comment]
Hmm @mcaskill any ideas what could cause this?

**Comment by Nihal12-dev** [comment]
All good issue's been sorted, it's an issue on my local computer cause i got another dev to check if it's working on his with the same composer version and it updated successfully ! Thanks for the help, Really appreciated that quick response. 

Have an awesome weekend !
