### ISSUE TITLE
Version mismatch when trying to install wp-all-import-pro 4.7.9

### ISSUE THREAD

**Issue by zment4** [junaidbhura/composer-wp-pro-plugins#65]
Trying to install wp-all-import-pro version 4.7.9 with composer with this in the composer.json:
```json
    {
      "type": "package",
      "package": {
        "name": "junaidbhura/wp-all-import-pro",
        "version": "4.7.9",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "https://www.wpallimport.com"
        },
        "require": {
          "junaidbhura/composer-wp-pro-plugins": "*"
        }
      }
    },   
```
Results in this error:
![image](https://github.com/junaidbhura/composer-wp-pro-plugins/assets/2785557/bdb8dfa7-4725-44e1-b579-425c053de90f)

I can workaround it by setting the version to 4.8.0, but shouldn't earlier versions be available as well? Also, this did work a few days prior.

**Comment by mcaskill** [comment]
Many commercial plugins, like WPAI, use [Easy Digital Downloads](https://easydigitaldownloads.com/) and its often configured in such a way that only the latest version can be retrieved.

In the internal HTTP requests we send to retrieve the plugin's download URL, [we do provide the locked package's version](https://github.com/junaidbhura/composer-wp-pro-plugins/blob/1.8.0/src/Plugins/WpAiPro.php#L79-L85), but EDD always returns the latest. Which is why you are receiving this error, in order to prevent one from accidentally downloading an unexpected version which could be breaking.

**Comment by zment4** [comment]
Is it possible to pin the version somehow? Tho in this case not a breaking thing, a minor annoyance most, but I can foresee a bunch of problems when not being able to pin to a specific version in case updates have happened...

**Comment by mcaskill** [comment]
<details>
<summary>Optional context about how Composer works</summary>

if need be: if a package's exact version is not defined the lock file (`composer.lock`), Composer will resolve an exact version from the constraint in the manifest file (`composer.json`). After the package's exact version is resolved, Composer will attempt to download the package from its source (as defined by Packagist or your manifest's `repositories`). This Composer plugin intercepts the placeholder repositories to fetch the file from each plugin's respective servers. Composer then stores a copy of the package in its cache. This cache is unique to each computer installing the Composer dependencies. If you don't have a copy of that package at that exact version from your lock file in your cache, Composer's going to fetch a fresh copy.

</details>

If you want to constrain the version of the WordPress plugin to something exact you should replace the asterisk `*` constraint (representing any version) with the version you support:

```json
"require": {
  "junaidbhura/wp-all-import-pro": "4.7.9"
}
```

I often scope WordPress plugins to the patch version:

```json5
"require": {
  "junaidbhura/wp-all-import-pro": "~4.7.0" // >=4.7.0 <4.8.0-0.
}
```

But I will still receive an error if all that is available is 4.8.0 or later.

If you are working with collaborators and they each have a copy of the project on their computers, they will have their own distinct caches. If they don't have a copy of the locked package version, they will encounter the error you initially posted about. You would have to send each other the cache files to help out (like downloading them from a shared staging environment).

**Comment by zment4** [comment]
Thanks for the detailed explanation. I feared something like this - so it's essentially up to the users of the package (ie. us, the developers) to have pinned version cache somewhere - which happens locally automatically, but if we want to have a setup for a clean environment, we'd have to provide this cache or repository ourselves. 

So essentially it's just the repository we are downloading from only provides the latest package - both composer and other parts in-between do send required version information, but it's not just... respected by the repository? More accustomed to other package-managers, I've grown used to the fact that multiple versions of packages are available, not just the latest, and it feels kind of... weird. 

Anyhow, I think this clears up the confusion quite nicely, and thank you for humoring me. As this is a non-issue (at least regarding you as the plugin developers), I'll close the issue out. Thanks again!

**Comment by mcaskill** [comment]
You are welcome.

I have not contacted any of these developers—I don't know if @junaidbhura has—but it could be worth contacting them to see if they only offer the latest as a policy or if the API needs to be changed. This Composer plugin is following EDD's API documentation.
