### ISSUE TITLE
ZIP archives in cache always use the same filename

### ISSUE THREAD

**Issue by mcaskill** [junaidbhura/composer-wp-pro-plugins#7]
When I bump the version number of a premium plugin to update it, I have to delete the cached ZIP archive before running `composer update` because it's always using the same file.

CLI:
```console
$ composer update junaidbhura/advanced-custom-fields-pro
Loading composer repositories with package information
Updating dependencies (including require-dev)                             
Package operations: 0 installs, 1 update, 0 removals
  - Updating junaidbhura/advanced-custom-fields-pro (5.7.10 => 5.7.13): Loading from cache
```

Cache:
```
~/.composer/cache/files/junaidbhura/advanced-custom-fields-pro/a1d4e989f9355a95800bd11210a4af208e067819.zip
```

`composer.json`
```json
"junaidbhura/advanced-custom-fields-pro": "*"
```
```json
{
    "type": "package",
    "package": {
        "name": "junaidbhura/advanced-custom-fields-pro",
        "version": "5.7.10",
        "type": "wordpress-muplugin",
        "dist": {
            "type": "zip",
            "url": "https://connect.advancedcustomfields.com/"
        },
        "require": {
            "junaidbhura/composer-wp-pro-plugins": "*"
        }
    }
}
```

This issue occurs with every plugin supported by this Composer plugin.

Am I doing something wrong?

Thanks

**Comment by junaidbhura** [comment]
@mcaskill I've noticed this as well. I usually run a `composer clear-cache` before any updates just to be safe.

Can't seem to figure out why this happens. Do you have any thoughts?

**Comment by mcaskill** [comment]
Ok. Good to know that I'm not crazy.

I'm unfamiliar with Composer's API so I don't know how it managers remote files.
The ZIP filename must be a hash of some kind. Maybe there's a way to customize the filename before/after its downloaded.

**Comment by junaidbhura** [comment]
Okay cool @mcaskill I'll take a deeper look when I get the time. In the mean time, please feel free to submit a PR.

**Comment by mcaskill** [comment]
I'll take a deeper look as well, when I find some time.
I've used this plugin on a couple of projects at work and a colleague is starting a third project using this plugin.

Thanks

**Comment by junaidbhura** [comment]
That's awesome, thanks :)

**Comment by rubas** [comment]
@junaidbhura, have you found the time to look into it? 

Clearing the cache everytime is wasting a lot of time - especially in our ci/deploy pipeline.

**Comment by mcaskill** [comment]
I haven't had a chance, on my end, to investigate the issue further.

**Comment by rubas** [comment]
This is not an issue, that we encounter with [private-composer-installer](https://github.com/ffraenz/private-composer-installer).

I'll add to my backlog and try to have a look at it later ...

**Comment by mcaskill** [comment]
I've noticed an odd behavior on some projects: Sometimes the pro WordPress plugins will update before the Composer plugin updates to v1.0.10, resulting in a continuance of the caching issue from before.

The solution I've found to this is either deleting the the WordPress plugins to force Composer to re-evaluate the packages and download a fresh copies using the correct dist URLs.

Alternatively, you can update the `composer.lock` manually by providing the WordPress plugins with the correctly hashed dist URL.
